### ISSUE TITLE
Use of deprecated GetNumber() method from Crossplane Runtime

### ISSUE THREAD

**Issue by stevendborrelli** [crossplane/function-sdk-go#58]
### What happened?

`resource/composite/composite.go` uses `GetNumber()`, which was deprecated and removed from Crossplane runtime In https://github.com/crossplane/crossplane-runtime/commit/11e9468944c9cbcdef5d2b310fbb3a470087adb0. This causes downstream functions to break if they update their go.mod. 

https://github.com/crossplane/function-sdk-go/blob/0a4b30c5daccf70b45c8130bbde3a1131f9ced67/resource/composite/composite.go#L312

**Comment by negz** [comment]
Using `GetNumber` was actually intentional here. See the comment above:

https://github.com/crossplane/function-sdk-go/blob/0a4b30c5daccf70b45c8130bbde3a1131f9ced67/resource/composite/composite.go#L298

I didn't consider the fact that it was deprecated though - I think having our own implementation of GetNumber as you've done in #59 makes sense here. Thanks!
